### ISSUE TITLE
Move to another platform for the Weekly Dev Meeting notes 

### ISSUE THREAD

**Issue by JamiesHQ** [jupyter/project-mgt#20]
Jupyter is currently using Hackpad for the weekly meeting notes and is experiencing data loss caused by network latency and other unknown causes. The team is more than ready to move to a new, more reliable platform. 

**Requirements**
_Must haves:_ 
1. Stability/No data loss
2. Real-time collaboration

_Nice to haves:_
1. Meeting note archive
2. Identifies individual contributors
3. Visually pleasing

**Plan**
1. Test/Evaluate etherpad, Dropbox Paper, SageMath, and Google Docs as potential solutions (List of Pros/Cons in project-mgt wiki)
2. Choose one
3. Implement

**Comment by willingc** [comment]
FYI @JamiesHQ Both Software Carpentry and Data Carpentry use and keep Etherpads. See there pad-of-pads http://pad.software-carpentry.org/pad-of-pads

**Comment by JamiesHQ** [comment]
Oh, clever! Thanks @willingc!

**Comment by jasongrout** [comment]
> It looked like the wiki you made indicated that there was not a way to archive.

I think we ought to archive (maybe just by manually copying when the editing frenzy has died down?) to a GitHub repo in our project, so that the notes are in a central permanent place. Perhaps this repo is a good one to store the notes in?

**Comment by fperez** [comment]
It seems we're settling on Dropbox Paper, and I'm good with that.

I've opened #61 so we track the migration instead of putting that here, as I think it's important we follow up on it separately.

I think we can close this for now, but I'll leave it to @JamiesHQ to make the final call.

**Comment by JamiesHQ** [comment]
Good idea, closing issue. Thanks!
