### ISSUE TITLE
PyCon | May 17–25, 2017 | PDX

### ISSUE THREAD

**Issue by JamiesHQ** [jupyter/project-mgt#3]
https://us.pycon.org/2017/about/

**Comment by yuvipanda** [comment]
I'm only present for the sprints (and part of Sunday).

Here's the things I want to accomplish!

- [ ] Get better docs on setting up to hack on jupyterhub/helm-chart, and how to hack on it 
- [x] Figure out what all the missing sections of Zero To JupyterHub guide are and track those - write a ToC (@yuvipanda @minrk @willingc)
- [x] Write a proposal for encrypting auth_state at rest in JupyterHub that meets @minrk's approval (threat analysis + pick tradeoffs we wanna make)
- [x] Document how to write a new s2i builder for new binder by helping @minrk write a conda builder (https://github.com/yuvipanda/builderhub/issues/17)
- [ ] Write more documentation on how the new binder is working, including how people can set up their own to test
- [x] Get consensus among JupyterHub team to move the new binder related repositories to the jupyterhub org.
- [x] Rename the binder related jupyter repositories so it makes sense for everyone
- [x] Figure out a better domain name / URL for the zero to jupyterhub guide (https://github.com/jupyter/jupyter.github.io/issues/208) 
- [x] Decide on versioning schemes for the helm chart / zero to jupyterhub guide
- [ ] Help @minrk finalize the pluggable proxies PR for JupyterHub
- [ ] Hack on ipython/ipynb a little bit

Probably won't get to all of them, but good to list these!

**Comment by yuvipanda** [comment]
I got @minrk to deploy and test binder, and also to hack on helm-chart. We haven't documented it yet tho. The pluggable Proxies PR got merged, but we want to do at least one more implementation before we release, so that isn't done yet. And I got no time to work on ipynb! :(

But we did a lot of work that wasn't listed here on binderhub. Shall list them here later :)

**Comment by willingc** [comment]
It was so wonderful to have @yuvipanda at PyCon for the sprints. I'm hoping that you will join us next year at PyCon 2018 in Cleveland. The strong Jupyter presence at the conference with @minrk, @mpacer, @Carreau, @yuvipanda, and @JamiesHQ had a very positive impact on both attendees and organizers. Great job everyone :D cc/ @fperez @ellisonbg
