### ISSUE TITLE
PyData Amsterdam | 8-9 April | Amsterdam

### ISSUE THREAD

**Issue by JamiesHQ** [jupyter/project-mgt#34]
http://pydata.org/amsterdam2017/

**Comment by SylvainCorlay** [comment]
Going to PyData Amsterdam to present of xtensor but will do some Jupyter outreach.

**Comment by Ruv7** [comment]
@SylvainCorlay - do you have a link to your presentation or any other info you would want to promote within the Jupyter newsletter? This is going out next Tuesday March 28 and I'm including this event in the "Upcoming Events" section. I see the title for your talk is: Debugging PySpark - Pretending to make sense of JVM stack traces. 

Can you send me one sentence to describe this further? It would go something like, "Jupyter contributor Sylvain Corlay will be presenting a talk titled Debugging PySpark - Pretending to make sense of JVM stack traces. He will focus on..." Lmk, thanks!

**Comment by takluyver** [comment]
I will also be there, but not presenting.
