### ISSUE TITLE
Computational Infrastructure for Geodynamics Webinar | Feb 9, 2017

### ISSUE THREAD

**Issue by ian-r-rose** [jupyter/project-mgt#40]
https://geodynamics.org/cig/events/webinars/

**Comment by JamiesHQ** [comment]
@ian-r-rose : Thanks for creating this issue- I noticed this didn't make it onto the board. Perhaps a better workflow is to create the card on the board first and then convert it to an issue. Looking forward to watching the video!

**Comment by JamiesHQ** [comment]
Video: https://youtu.be/SfbCaXlRWHc
