### ISSUE TITLE
PyData Ann Arbor first meetup |  March 2 | Ann Arbor

### ISSUE THREAD

**Issue by JamiesHQ** [jupyter/project-mgt#42]
https://www.meetup.com/PyData-Ann-Arbor/

**Comment by JamiesHQ** [comment]
@willingc - how did you create the card on the board? I like how that worked! Much easier to create the card first then add it to the appropriate repo.

**Comment by JamiesHQ** [comment]
@willingc - nevermind- figured it out. Cool! Much better for the devs! I'll share it in the meeting next week.

**Comment by willingc** [comment]
Lol. I don't know what I did. I made the card and then got confused so ignored the rest. I'm glad my inability to know what I was doing helped you ;-)
