### ISSUE TITLE
Codeland | 21-22 April | NYC

### ISSUE THREAD

**Issue by willingc** [jupyter/project-mgt#52]

**Comment by Ruv7** [comment]
@willingc - I'd like to include this in the next newsletter. Can you help me with a lil blurb for it? Here is what I have placeheld but I'm happy to update per your suggestions. Lmk.

Codeland: April 21–22, 2017, NYC. Jupyter contributors Carol Willing and Safia Abdalla will be speaking on a panel where the topic is Open Source. http://codelandconf.com/
